AT-Market/AT-Market/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AT_Market.Models
{
    public class Order
    {   
        [Key]
        public  int OrderID { get; set; }

        public  DateTime DataOrder { get; set; }

        public int CustomerID { get; set; }

        public OrderStatus OrderStatus { get; set; }

        public virtual Customer Customer { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

       
    }
}

AT-Market/AT-Market/ViewModels/OrderView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AT_Market.Models;

namespace AT_Market.ViewModels
{
    public class OrderView
    {
        public Customer Customer { get; set; }

        public ProductOrder Product { get; set; }

        public List<ProductOrder> Products { get; set; }
    }
}

AT-Market/AT-Market/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AT_Market.Helpers;
using AT_Market.Models;
using AT_Market.ViewModels;

namespace AT_Market.Controllers
{
    public class OrdersController : Controller
    {
        private AT_MarketContext db=new AT_MarketContext();

        // GET: Orders
        public ActionResult NewOrder()
        {
            var orderView = new OrderView();
            orderView.Customer=new Customer();
            orderView.Products=new List<ProductOrder>();

            Session["orderView"] = orderView;

            ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(),"CustomerID","Name");

            return View(orderView);
        }

        public ActionResult AddProduct()
        {
            ViewBag.ProductID = new SelectList(CombosHelper.GetProducts(), "ProductID", "Description");

            return View();
        }

        [HttpPost]
        public ActionResult NewOrder(OrderView orderView)
        {
            orderView = Session["orderView"] as OrderView;

            var CustomerID = int.Parse(Request["CustomerID"]);

            if (CustomerID == 0)
            {
                ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");
                ViewBag.Error = "Deve selecionar um cliente";

                return View(orderView);
            }

            var customer = db.Customers.Find(CustomerID);

            if (customer == null)
            {
                ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");
                ViewBag.Error = "O cliente não existe";
               
                return View(orderView);
            }

            if (orderView.Products.Count == 0)
            {
                ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");
                ViewBag.Error = "Não se pode criar encomenda sem artigos";
               
                return View(orderView);
            }

            int orderID = 0;

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var order = new Order
                    {
                        CustomerID = CustomerID,
                        DataOrder = DateTime.Now,
                        OrderStatus = OrderStatus.Created
                    };

                    db.Orders.Add(order);
                    db.SaveChanges();

                    orderID = order.OrderID;
                    ////
                      // int n = 2;
                      // int x = n / 0;

                    foreach (var item in orderView.Products)
                    {
                        var orderDetail = new OrderDetail
                        {
                            Description = item.Description,
                            Price = item.Price,
                            Quantity = item.Quantity,
                            OrderID = orderID,
                            ProductID = item.ProductID
                        };

                        db.OrderDetails.Add(orderDetail);
                        db.SaveChanges();
                    }

                    transaction.Commit();
                }
                catch (Exception e)
                {
                    transaction.Rollback();

                    ViewBag.Error = $"Erro: {e.Message}";
                    ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");

                    return View(orderView);
                }

            }


            ViewBag.Message = $"A Encomenda: {orderID} foi efetuada com sucesso!";

            ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");
           
            orderView = new OrderView();
            orderView.Customer=new Customer();
            orderView.Products=new List<ProductOrder>();

            Session["orderView"] = orderView;

            return View(orderView);
            //return RedirectToAction("NewOrder");
        }

        [HttpPost]
        public ActionResult AddProduct(ProductOrder productOrder)
        {
            var orderView = Session["orderView"] as OrderView;

            var ProductID = int.Parse(Request["ProductID"]);
            //Caso nao haja produto escolido
            if (ProductID == 0)
            {
                ViewBag.ProductID = new SelectList(CombosHelper.GetProducts(), "ProductID", "Description");
                ViewBag.Error = "Deve selecionar um produto";

                return View(productOrder);
            }

            //Verificar se produto existe
            var Product = db.Products.Find(ProductID);

            if (Product == null)
            {
                ViewBag.ProductID = new SelectList(CombosHelper.GetProducts(), "ProductID", "Description");
                ViewBag.Error = "Produto não existe";

                return View(productOrder);

            }

            productOrder = orderView.Products.Find(p => p.ProductID == ProductID);

            if (productOrder == null)
            {
                productOrder = new ProductOrder
                {
                    Description = Product.Description,
                    Price = Product.Price,
                    ProductID = Product.ProductID,
                    Quantity = float.Parse(Request["Quantity"])
                };

                orderView.Products.Add(productOrder);

            }
            else
            {
                productOrder.Quantity += float.Parse(Request["Quantity"]);
            }

            ViewBag.CustomerID = new SelectList(CombosHelper.GetCustomersNames(), "CustomerID", "Name");

            return View("NewOrder", orderView);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AT-Market/AT-Market/Views/Orders/AddProduct.cshtml
@model AT_Market.Models.ProductOrder
@{
    ViewBag.Title = "Adiciona Produto";
}

<h2>Escolher Produtos</h2>
@ViewBag.Error

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">



    <div class="form-group">
        @Html.LabelFor(model => model.ProductID, "Produto", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="submit" value="Adiciona Produto" class="btn btn-default" />

</div>
}

<div>
    @Html.ActionLink("Back to List", "NewOrder")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AT-Market/AT-Market/Views/Orders/NewOrder.cshtml
@model AT_Market.ViewModels.OrderView
@{
    ViewBag.Title = "Nova Encomenda";
}

<h2>Nova Encomenda</h2>
<h3>@ViewBag.Error</h3>
<h3>@ViewBag.Message</h3>


@using (Html.BeginForm("NewOrder","Orders",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

     

        <div class="form-group">
            @Html.LabelFor(model => model.Customer.CustomerID, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <br/>
        <br/>

        @Html.ActionLink("Adiciona Produto","AddProduct", new{ }, new{ @class="btn btn-primary"})
        
        <input type="submit" value="Encomendar" id="NewOrder" class="btn btn-success" />
   
    </div>

    <h2>Detalhes de Encomenda</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Value)
            </th>
        <th></th>
        </tr>

        @for (int i=0;i<Model.Products.Count;i++) 
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Products[i].Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Products[i].Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Products[i].Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Products[i].Value)
                </td>
              
                <td>              
                    @Html.ActionLink("Details", "Details", new { id = Model.Products[i].ProductID }) |
                    @Html.ActionLink("Delete", "Delete", new { id= Model.Products[i].ProductID })
                </td>
            </tr>
        }

    </table>
}